# Generated by Django 5.1.2 on 2025-08-11 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0011_alter_loanguarantor_loan_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyfund',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='emergencyfund',
            name='user',
        ),
        migrations.AddField(
            model_name='emergencyfund',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
