# Generated by Django 5.1.2 on 2025-08-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0012_remove_emergencyfund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('M-pesa', 'M-pesa'), ('Cash', 'Cash')], default='M-pesa', max_length=20),
        ),
    ]
