# Generated by Django 5.1.2 on 2025-08-13 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0013_transaction_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanguarantor',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='loanguarantor',
            name='guarantor',
        ),
        migrations.AddField(
            model_name='user',
            name='date_Approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('guarantor1_confirmed', models.BooleanField(default=False)),
                ('guarantor2_confirmed', models.BooleanField(default=False)),
                ('treasurer_approved', models.BooleanField(default=False)),
                ('treasurer_rejected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_guarantors', 'Pending Guarantor Confirmation'), ('pending_treasurer', 'Pending Treasurer Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_guarantors', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guarantor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_loans_as_g1', to=settings.AUTH_USER_MODEL)),
                ('guarantor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_loans_as_g2', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='The user who initiated the loan request.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requested_for', models.ForeignKey(help_text='The member for whom the loan is being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='sacco.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LoanGuarantorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_actions', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_actions', to='sacco.loanrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='LoanGuarantor',
        ),
    ]
