# Generated by Django 5.1.2 on 2025-08-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0014_remove_loanguarantor_loan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='requested_for',
            new_name='borrower',
        ),
    ]
