# Generated by Django 5.1.2 on 2025-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0015_rename_requested_for_loanrequest_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanguarantoraction',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='True if the guarantor confirms the loan request, False if they decline.'),
        ),
    ]
