# Generated by Django 5.1.2 on 2025-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0016_alter_loanguarantoraction_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanguarantoraction',
            name='confirmed',
            field=models.BooleanField(default=None, help_text='None = pending, True = accepted, False = rejected', null=True),
        ),
    ]
