# Generated by Django 5.1.2 on 2025-08-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0017_alter_loanguarantoraction_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='guarantor1_confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='guarantor2_confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='treasurer_approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='treasurer_rejected',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
