# Generated by Django 5.1.2 on 2025-08-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0018_alter_loanrequest_guarantor1_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='amountApproved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='due_date',
            field=models.DateField(blank=True, help_text='The date by which the loan must be repaid.', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
