# Generated by Django 5.1.2 on 2025-08-22 15:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0019_loanrequest_amountapproved_loanrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='balance_after_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance after this payment', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, help_text='Installment sequence number', null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa')], default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Late payment penalty', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='amount_repaid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount actually approved and repaid incrementally.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
