# Generated by Django 5.1.2 on 2025-08-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0020_loanrepayment_approved_at_loanrepayment_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('guarantor_approval', 'Guarantor Approval'), ('treasurer_approval', 'Treasurer Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('repayment_in_progress', 'Repayment In Progress'), ('repaid', 'Repaid')], default='pending_guarantors', max_length=30),
        ),
    ]
